[workspace]
members = [
    "sz_common",
    "sz_aes_plugin",
    "sz_dummy_plugin"
]
resolver = "3"

[workspace.dependencies]
sz_common = { path = "sz_common" }
aes = "0.8"
cbc = "0.1"
base64 = "0.22"
rand = "0.8"
zeroize = "1.7"
thiserror = "1.0"
libc = "0.2"
proptest = "1.4"
cbindgen = "0.26"
